FROM python:3.11-slim

WORKDIR /app

COPY requirements.streamlit.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.streamlit.txt

COPY . .

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=10000"]